# Generated by Django 3.0.3 on 2020-03-03 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('word_cnt', models.PositiveIntegerField(default=0)),
                ('evaluation', models.TextField(choices=[(1, '◎'), (2, '○'), (3, '△'), (4, '×')])),
                ('coment', models.CharField(max_length=255)),
                ('date_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tadoku_calendar.Date')),
            ],
        ),
    ]
