# Generated by Django 3.0.3 on 2020-03-04 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tadoku_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date_key',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='evaluation',
            field=models.IntegerField(choices=[(1, '◎'), (2, '○'), (3, '△'), (4, '×')]),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
