# Generated by Django 3.0.3 on 2020-03-11 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tadoku_calendar', '0002_auto_20200304_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='level',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='series',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
